---
output:
  word_document: default
  html_document: default
---
### K Nearest Neighbor


```{r}
library(ISLR)
str(Caravan)
summary(Caravan$Purchase)
```

```{r}
any(is.na(Caravan))
```

```{r}
var(Caravan[,1])
var(Caravan[,2])
```

```{r}
purchase <- Caravan[,86]
```

# Standardize Dataset in R

```{r}
standardized.Caravan <- scale(Caravan[,-86])

print(var(standardized.Caravan[,1]))
print(var(standardized.Caravan[,2]))
```


# Test
```{r}
test.index <- 1:1000
test.data <- standardized.Caravan[test.index,]
test.purchase <- purchase[test.index]
```

# Train

```{r}
train.data <- standardized.Caravan[-test.index,]
train.purchase <- purchase[-test.index]
```

# KNN Model

```{r}
library(class)
```

```{r}
set.seed(101)

predicted.purchase <- knn(train.data,test.data,train.purchase,k=1)

print(head(predicted.purchase))
```

# Using Different K value Where k=3

```{r}
predicted.purchase <- knn(train.data,test.data,train.purchase,k=3)
mean(test.purchase != predicted.purchase)
```

# k=5

```{r}
predicted.purchase <- knn(train.data,test.data,train.purchase,k=5)
mean(test.purchase != predicted.purchase)
```

# Null vs. NA

```{r}
predicted.purchase = NULL
error.rate = NULL
```

```{r}
for(i in 1:20){
  set.seed(101)
  predicted.purchase = knn(train.data,test.data,train.purchase,k=i)
  error.rate[i] = mean(test.purchase != predicted.purchase)
}
```


```{r}
print(error.rate)
```

# Elbow Method

```{r}
library(ggplot2)
```

```{r}
k.values <- 1:20
```

```{r}
error.df <- data.frame(error.rate,k.values)

error.df
```


# Determining Misclassification

```{r}
ggplot(error.df,aes(x=k.values,y=error.rate)) + geom_point()+ geom_line(lty="dotted",color='red')
```
