# Neural Nets Project


## Reading the Data

```{r}
df <- read.csv('bank_note_data.csv')
head(df)
```

## Checking for NA Values

```{r}
any(is.na(df))
```

## Train Test Split

```{r}
library(caTools)
set.seed(101)
split <- sample.split(df$Class,SplitRatio = 0.7)

train <- subset(df,split==TRUE)
test <- subset(df,split==FALSE)
```


## Neural Nets

```{r}
library(neuralnet)

nn <- neuralnet(Class ~ Image.Var + Image.Skew + Image.Curt + Entropy, 
          data=train, hidden = c(5,3), linear.output = FALSE)
predicted.nn.values <- compute(nn,test[1:4])
head(predicted.nn.values$net.result)
```

## Rounding the Data

```{r}
predictions <- sapply(predicted.nn.values$net.result,round)
head(predictions)
```

## Confusion Matrix
```{r}
table(predictions, test$Class)
```

## Random Forest

```{r}
library(randomForest)

df$Class <- factor(df$Class)
library(caTools)
set.seed(101)
split = sample.split(df$Class, SplitRatio = 0.70)
```

```{r}
train = subset(df, split == TRUE)
test = subset(df, split == FALSE)
```

```{r}
model <- randomForest(Class ~ Image.Var + 
    Image.Skew + Image.Curt + Entropy,data=train)

rf.pred <- predict(model,test)

table(rf.pred,test$Class)
```
### Models are very close to each other.